### PR TITLE
Start sending viewport to the flutter app on ios

### PR DESCRIPTION
**Pull request by sidneyorlovski**

### CODE REVIEW

**Review by mugbug — APPROVED** [review]
LGTM!

**Review by andrelewkatz — APPROVED** [review]
LGTM! 🚀

**Comment by matanshukry** [comment]
Thanks for the pull request @sidneyorlovski !

Will release a new version with that soon.

**Comment by simkepal** [comment]
Hello,

Is there any timeline on this one?

Thank you!

**Pull request merged**
